### ISSUE TITLE
Orders Page Error

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#24]
This issue occurs when a subscriber attempts to login to their account.

http://theultimaterepairsystem.com/orders

```
[2017-01-06 18:34:10] production.ERROR: ErrorException: Trying to get property of non-object in /var/www/turs/storage/framework/views/5aa60b50c80bda35e0ea6f23b44d723aa0f03302.php:21
Stack trace:
#0 /var/www/turs/storage/framework/views/5aa60b50c80bda35e0ea6f23b44d723aa0f03302.php(21): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/var/www/turs/s...', 21, Array)
#1 /var/www/turs/bootstrap/cache/compiled.php(15456): include('/var/www/turs/s...')
#2 /var/www/turs/bootstrap/cache/compiled.php(15493): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/turs/s...', Array)
#3 /var/www/turs/bootstrap/cache/compiled.php(15325): Illuminate\View\Engines\CompilerEngine->get('/var/www/turs/r...', Array)
#4 /var/www/turs/bootstrap/cache/compiled.php(15313): Illuminate\View\View->getContents()
#5 /var/www/turs/bootstrap/cache/compiled.php(15297): Illuminate\View\View->renderContents()
#6 /var/www/turs/app/Http/Controllers/OrderController.php(33): Illuminate\View\View->render()
#7 [internal function]: App\Http\Controllers\OrderController->index()
#8 /var/www/turs/bootstrap/cache/compiled.php(9419): call_user_func_array(Array, Array)
#9 /var/www/turs/bootstrap/cache/compiled.php(9446): Illuminate\Routing\Controller->callAction('index', Array)
#10 /var/www/turs/bootstrap/cache/compiled.php(8500): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\OrderController), 'index')
#11 /var/www/turs/bootstrap/cache/compiled.php(8481): Illuminate\Routing\Route->runController()
#12 /var/www/turs/bootstrap/cache/compiled.php(8190): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/turs/app/Http/Middleware/SetRedirectUrl.php(24): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/turs/bootstrap/cache/compiled.php(9904): App\Http\Middleware\SetRedirectUrl->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/turs/app/Http/Middleware/SubdomainManager.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/turs/bootstrap/cache/compiled.php(9904): App\Http\Middleware\SubdomainManager->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/turs/app/Http/Middleware/DenyAccessForSuperAdmin.php(26): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/turs/bootstrap/cache/compiled.php(9904): App\Http\Middleware\DenyAccessForSuperAdmin->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/turs/app/Http/Middleware/LogoutIfEmailNotVerified.php(24): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/turs/bootstrap/cache/compiled.php(9904): App\Http\Middleware\LogoutIfEmailNotVerified->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/turs/vendor/laravel/spark/src/Http/Middleware/VerifyUserHasTeam.php(22): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/turs/bootstrap/cache/compiled.php(9904): Laravel\Spark\Http\Middleware\VerifyUserHasTeam->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/turs/vendor/laravel/spark/src/Http/Middleware/CreateFreshApiToken.php(40): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/turs/bootstrap/cache/compiled.php(9904): Laravel\Spark\Http\Middleware\CreateFreshApiToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/turs/bootstrap/cache/compiled.php(10012): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/turs/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/turs/bootstrap/cache/compiled.php(3164): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/turs/bootstrap/cache/compiled.php(13560): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/turs/bootstrap/cache/compiled.php(11983): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/turs/bootstrap/cache/compiled.php(13306): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/turs/bootstrap/cache/compiled.php(13243): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/turs/bootstrap/cache/compiled.php(9889): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /var/www/turs/bootstrap/cache/compiled.php(8191): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#55 /var/www/turs/bootstrap/cache/compiled.php(8182): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#56 /var/www/turs/bootstrap/cache/compiled.php(8173): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#57 /var/www/turs/bootstrap/cache/compiled.php(2471): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#58 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/turs/bootstrap/cache/compiled.php(3226): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/turs/bootstrap/cache/compiled.php(9889): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 /var/www/turs/bootstrap/cache/compiled.php(2415): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 /var/www/turs/bootstrap/cache/compiled.php(2399): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#65 /var/www/turs/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#66 {main}

Next ErrorException: Trying to get property of non-object (View: /var/www/turs/resources/views/order/table.blade.php) in /var/www/turs/storage/framework/views/5aa60b50c80bda35e0ea6f23b44d723aa0f03302.php:21
Stack trace:
#0 /var/www/turs/bootstrap/cache/compiled.php(15458): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /var/www/turs/bootstrap/cache/compiled.php(15493): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/turs/s...', Array)
#2 /var/www/turs/bootstrap/cache/compiled.php(15325): Illuminate\View\Engines\CompilerEngine->get('/var/www/turs/r...', Array)
#3 /var/www/turs/bootstrap/cache/compiled.php(15313): Illuminate\View\View->getContents()
#4 /var/www/turs/bootstrap/cache/compiled.php(15297): Illuminate\View\View->renderContents()
#5 /var/www/turs/app/Http/Controllers/OrderController.php(33): Illuminate\View\View->render()
#6 [internal function]: App\Http\Controllers\OrderController->index()
#7 /var/www/turs/bootstrap/cache/compiled.php(9419): call_user_func_array(Array, Array)
#8 /var/www/turs/bootstrap/cache/compiled.php(9446): Illuminate\Routing\Controller->callAction('index', Array)
#9 /var/www/turs/bootstrap/cache/compiled.php(8500): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\OrderController), 'index')
#10 /var/www/turs/bootstrap/cache/compiled.php(8481): Illuminate\Routing\Route->runController()
#11 /var/www/turs/bootstrap/cache/compiled.php(8190): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/turs/app/Http/Middleware/SetRedirectUrl.php(24): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/turs/bootstrap/cache/compiled.php(9904): App\Http\Middleware\SetRedirectUrl->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/turs/app/Http/Middleware/SubdomainManager.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/turs/bootstrap/cache/compiled.php(9904): App\Http\Middleware\SubdomainManager->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/turs/app/Http/Middleware/DenyAccessForSuperAdmin.php(26): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/turs/bootstrap/cache/compiled.php(9904): App\Http\Middleware\DenyAccessForSuperAdmin->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/turs/app/Http/Middleware/LogoutIfEmailNotVerified.php(24): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/turs/bootstrap/cache/compiled.php(9904): App\Http\Middleware\LogoutIfEmailNotVerified->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/turs/vendor/laravel/spark/src/Http/Middleware/VerifyUserHasTeam.php(22): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/turs/bootstrap/cache/compiled.php(9904): Laravel\Spark\Http\Middleware\VerifyUserHasTeam->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/turs/vendor/laravel/spark/src/Http/Middleware/CreateFreshApiToken.php(40): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/turs/bootstrap/cache/compiled.php(9904): Laravel\Spark\Http\Middleware\CreateFreshApiToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/turs/bootstrap/cache/compiled.php(10012): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/turs/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/turs/bootstrap/cache/compiled.php(3164): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/turs/bootstrap/cache/compiled.php(13560): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/turs/bootstrap/cache/compiled.php(11983): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/turs/bootstrap/cache/compiled.php(13306): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/turs/bootstrap/cache/compiled.php(13243): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /var/www/turs/bootstrap/cache/compiled.php(9889): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/turs/bootstrap/cache/compiled.php(8191): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 /var/www/turs/bootstrap/cache/compiled.php(8182): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#55 /var/www/turs/bootstrap/cache/compiled.php(8173): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#56 /var/www/turs/bootstrap/cache/compiled.php(2471): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#57 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#58 /var/www/turs/bootstrap/cache/compiled.php(3226): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /var/www/turs/bootstrap/cache/compiled.php(9889): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/turs/bootstrap/cache/compiled.php(2415): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#63 /var/www/turs/bootstrap/cache/compiled.php(2399): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#64 /var/www/turs/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#65 {main}  

```

**Comment by jcergolj** [comment]
Resolved and pushed to `develop` branch.
