### ISSUE TITLE
Create Device Not Populating Make and Model Select Elements

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#29]
From issue https://github.com/Samyoul/The-ultimate-repair-system-issues/issues/6

There is currently a bug on selecting the make and model, but this will be obsolete after the above feature has been implemented.

![employee new repair order](https://cloud.githubusercontent.com/assets/5702426/21545000/d665192e-cdcb-11e6-927c-2a388f81dbb6.png)

**Comment by jcergolj** [comment]
Does `Make` and `Model` have records in the table? 

/owners/models
/owners/makes

**Comment by Samyoul** [comment]
Yes, please see below.

![owner models](https://cloud.githubusercontent.com/assets/5702426/21845842/35cef824-d7ec-11e6-99d2-013e8b868aad.png)
![owner makes](https://cloud.githubusercontent.com/assets/5702426/21845843/35d0d63a-d7ec-11e6-8670-d4c197a11f9b.png)

**Comment by Samyoul** [comment]
Do you know if this is an issue that can be resolved today?

**Comment by jcergolj** [comment]
The problem is that I can't reproduce the bug locally. Locally everything works. Can you send me database dump.

**Comment by jcergolj** [comment]
Were makes and models imported or created one by one? Models have wrong makes ids.

Valid makes ids for models where team_id = 2 are from 27 to 52.

**Comment by Samyoul** [comment]
The makes and models were imported when the new account was created.

**Comment by jcergolj** [comment]
Ok, replace `make_id` in `models` table and everything should be fine. Valid `make_id` are 27 - 52. So where team_id = 2.

**Comment by Samyoul** [comment]
Do you know what may have caused this issue?

**Comment by jcergolj** [comment]
My fist guess would be this:

https://github.com/Samyoul/The-ultimate-repair-system/blob/master/app/Http/Controllers/Admins/DataImportController.php#L129

I am not sure if array with multiple keys can be used in `where`. What are you looking at is
$class::where('filed', $value)->where('team_id', auth()->user()->currentTeam->id)->first();

**Comment by Samyoul** [comment]
Ah, I think we are talking about two different imports.

Only the superadmin used the data import functionality.

The subscriber had their data automatically imported from the superadmin default data during the subscriber creation process.

**Comment by jcergolj** [comment]
Ok, can you create a new user and see if the same bug occurs?

**Comment by Samyoul** [comment]
I've created a new subscriber, the same issue occurs

**Comment by jcergolj** [comment]
I'll take a look at both bugs tomorrow morning.

**Comment by jcergolj** [comment]
fixed.

**Comment by Samyoul** [comment]
Currently getting the following error on subscriber creation:

```
[2017-01-11 22:57:41] production.ERROR: ErrorException: Trying to get property of non-object in /var/www/turs/app/Listeners/CopyDefaultModels.php:39
Stack trace:
#0 /var/www/turs/app/Listeners/CopyDefaultModels.php(39): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/var/www/turs/a...', 39, Array)
#1 [internal function]: App\Listeners\CopyDefaultModels->handle(Object(App\Events\UserRegistered))
#2 /var/www/turs/vendor/laravel/framework/src/Illuminate/Events/CallQueuedHandler.php(42): call_user_func_array(Array, Array)
#3 /var/www/turs/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(73): Illuminate\Events\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#4 /var/www/turs/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(42): Illuminate\Queue\Jobs\Job->fire()
#5 /var/www/turs/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(263): Illuminate\Queue\SyncQueue->push('Illuminate\\Even...', Array)
#6 /var/www/turs/bootstrap/cache/compiled.php(10193): Illuminate\Queue\QueueManager->__call('push', Array)
#7 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(App\Events\UserRegistered))
#8 /var/www/turs/bootstrap/cache/compiled.php(10161): call_user_func_array(Object(Closure), Array)
#9 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(App\Events\UserRegistered))
#10 /var/www/turs/bootstrap/cache/compiled.php(10101): call_user_func_array(Object(Closure), Array)
#11 /var/www/turs/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(478): Illuminate\Events\Dispatcher->fire('App\\Events\\User...')
#12 /var/www/turs/app/Providers/SparkServiceProvider.php(150): event(Object(App\Events\UserRegistered))
#13 [internal function]: Laravel\Spark\Interactions\Auth\CreateUser->App\Providers\{closure}(Object(Laravel\Spark\Http\Requests\Auth\StripeRegisterRequest))
#14 /var/www/turs/vendor/laravel/spark/src/Configuration/CallsInteractions.php(76): call_user_func_array(Object(Closure), Array)
#15 /var/www/turs/vendor/laravel/spark/src/Configuration/CallsInteractions.php(53): Laravel\Spark\Spark::callSwappedInteraction('CreateUser@hand...', Array, 'Laravel\\Spark\\C...')
#16 /var/www/turs/vendor/laravel/spark/src/Interactions/Auth/Register.php(43): Laravel\Spark\Spark::interact('Laravel\\Spark\\C...', Array)
#17 /var/www/turs/vendor/laravel/spark/src/Interactions/Auth/Register.php(31): Laravel\Spark\Interactions\Auth\Register->createUser(Object(Laravel\Spark\Http\Requests\Auth\StripeRegisterRequest))
#18 /var/www/turs/vendor/laravel/framework/src/Illuminate/Database/Connection.php(569): Laravel\Spark\Interactions\Auth\Register->Laravel\Spark\Interactions\Auth\{closure}(Object(Illuminate\Database\MySqlConnection))
#19 /var/www/turs/bootstrap/cache/compiled.php(11794): Illuminate\Database\Connection->transaction(Object(Closure))
#20 /var/www/turs/bootstrap/cache/compiled.php(6321): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#21 /var/www/turs/vendor/laravel/spark/src/Interactions/Auth/Register.php(32): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#22 [internal function]: Laravel\Spark\Interactions\Auth\Register->handle(Object(Laravel\Spark\Http\Requests\Auth\StripeRegisterRequest))
#23 /var/www/turs/vendor/laravel/spark/src/Configuration/CallsInteractions.php(56): call_user_func_array(Array, Array)
#24 /var/www/turs/vendor/laravel/spark/src/Http/Controllers/Auth/RegisterController.php(59): Laravel\Spark\Spark::interact('Laravel\\Spark\\C...', Array)
#25 [internal function]: Laravel\Spark\Http\Controllers\Auth\RegisterController->register(Object(Laravel\Spark\Http\Requests\Auth\StripeRegisterRequest))
#26 /var/www/turs/bootstrap/cache/compiled.php(9419): call_user_func_array(Array, Array)
#27 /var/www/turs/bootstrap/cache/compiled.php(9446): Illuminate\Routing\Controller->callAction('register', Array)
#28 /var/www/turs/bootstrap/cache/compiled.php(8500): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Auth\RegisterController), 'register')
#29 /var/www/turs/bootstrap/cache/compiled.php(8481): Illuminate\Routing\Route->runController()
#30 /var/www/turs/bootstrap/cache/compiled.php(8190): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#31 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/turs/app/Http/Middleware/RedirectIfAuthenticated.php(24): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/turs/bootstrap/cache/compiled.php(9904): App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/turs/vendor/laravel/spark/src/Http/Middleware/VerifyUserHasTeam.php(22): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/turs/bootstrap/cache/compiled.php(9904): Laravel\Spark\Http\Middleware\VerifyUserHasTeam->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/turs/vendor/laravel/spark/src/Http/Middleware/CreateFreshApiToken.php(40): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/turs/bootstrap/cache/compiled.php(9904): Laravel\Spark\Http\Middleware\CreateFreshApiToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/turs/bootstrap/cache/compiled.php(10012): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/turs/bootstrap/cache/compiled.php(3164): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/turs/bootstrap/cache/compiled.php(13560): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/turs/bootstrap/cache/compiled.php(11983): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/turs/bootstrap/cache/compiled.php(13306): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/turs/bootstrap/cache/compiled.php(13243): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/turs/bootstrap/cache/compiled.php(9889): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/turs/bootstrap/cache/compiled.php(8191): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#61 /var/www/turs/bootstrap/cache/compiled.php(8182): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#62 /var/www/turs/bootstrap/cache/compiled.php(8173): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#63 /var/www/turs/bootstrap/cache/compiled.php(2471): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#64 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#65 /var/www/turs/bootstrap/cache/compiled.php(3226): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /var/www/turs/bootstrap/cache/compiled.php(9889): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /var/www/turs/bootstrap/cache/compiled.php(2415): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#70 /var/www/turs/bootstrap/cache/compiled.php(2399): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#71 /var/www/turs/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#72 {main}  
[2017-01-11 23:07:16] production.ERROR: ErrorException: Trying to get property of non-object in /var/www/turs/app/Listeners/CopyDefaultModels.php:39
Stack trace:
#0 /var/www/turs/app/Listeners/CopyDefaultModels.php(39): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/var/www/turs/a...', 39, Array)
#1 [internal function]: App\Listeners\CopyDefaultModels->handle(Object(App\Events\UserRegistered))
#2 /var/www/turs/vendor/laravel/framework/src/Illuminate/Events/CallQueuedHandler.php(42): call_user_func_array(Array, Array)
#3 /var/www/turs/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(73): Illuminate\Events\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#4 /var/www/turs/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(42): Illuminate\Queue\Jobs\Job->fire()
#5 /var/www/turs/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(263): Illuminate\Queue\SyncQueue->push('Illuminate\\Even...', Array)
#6 /var/www/turs/bootstrap/cache/compiled.php(10193): Illuminate\Queue\QueueManager->__call('push', Array)
#7 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(App\Events\UserRegistered))
#8 /var/www/turs/bootstrap/cache/compiled.php(10161): call_user_func_array(Object(Closure), Array)
#9 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(App\Events\UserRegistered))
#10 /var/www/turs/bootstrap/cache/compiled.php(10101): call_user_func_array(Object(Closure), Array)
#11 /var/www/turs/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(478): Illuminate\Events\Dispatcher->fire('App\\Events\\User...')
#12 /var/www/turs/app/Providers/SparkServiceProvider.php(150): event(Object(App\Events\UserRegistered))
#13 [internal function]: Laravel\Spark\Interactions\Auth\CreateUser->App\Providers\{closure}(Object(Laravel\Spark\Http\Requests\Auth\StripeRegisterRequest))
#14 /var/www/turs/vendor/laravel/spark/src/Configuration/CallsInteractions.php(76): call_user_func_array(Object(Closure), Array)
#15 /var/www/turs/vendor/laravel/spark/src/Configuration/CallsInteractions.php(53): Laravel\Spark\Spark::callSwappedInteraction('CreateUser@hand...', Array, 'Laravel\\Spark\\C...')
#16 /var/www/turs/vendor/laravel/spark/src/Interactions/Auth/Register.php(43): Laravel\Spark\Spark::interact('Laravel\\Spark\\C...', Array)
#17 /var/www/turs/vendor/laravel/spark/src/Interactions/Auth/Register.php(31): Laravel\Spark\Interactions\Auth\Register->createUser(Object(Laravel\Spark\Http\Requests\Auth\StripeRegisterRequest))
#18 /var/www/turs/vendor/laravel/framework/src/Illuminate/Database/Connection.php(569): Laravel\Spark\Interactions\Auth\Register->Laravel\Spark\Interactions\Auth\{closure}(Object(Illuminate\Database\MySqlConnection))
#19 /var/www/turs/bootstrap/cache/compiled.php(11794): Illuminate\Database\Connection->transaction(Object(Closure))
#20 /var/www/turs/bootstrap/cache/compiled.php(6321): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#21 /var/www/turs/vendor/laravel/spark/src/Interactions/Auth/Register.php(32): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#22 [internal function]: Laravel\Spark\Interactions\Auth\Register->handle(Object(Laravel\Spark\Http\Requests\Auth\StripeRegisterRequest))
#23 /var/www/turs/vendor/laravel/spark/src/Configuration/CallsInteractions.php(56): call_user_func_array(Array, Array)
#24 /var/www/turs/vendor/laravel/spark/src/Http/Controllers/Auth/RegisterController.php(59): Laravel\Spark\Spark::interact('Laravel\\Spark\\C...', Array)
#25 [internal function]: Laravel\Spark\Http\Controllers\Auth\RegisterController->register(Object(Laravel\Spark\Http\Requests\Auth\StripeRegisterRequest))
#26 /var/www/turs/bootstrap/cache/compiled.php(9419): call_user_func_array(Array, Array)
#27 /var/www/turs/bootstrap/cache/compiled.php(9446): Illuminate\Routing\Controller->callAction('register', Array)
#28 /var/www/turs/bootstrap/cache/compiled.php(8500): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Auth\RegisterController), 'register')
#29 /var/www/turs/bootstrap/cache/compiled.php(8481): Illuminate\Routing\Route->runController()
#30 /var/www/turs/bootstrap/cache/compiled.php(8190): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#31 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/turs/app/Http/Middleware/RedirectIfAuthenticated.php(24): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/turs/bootstrap/cache/compiled.php(9904): App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/turs/vendor/laravel/spark/src/Http/Middleware/VerifyUserHasTeam.php(22): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/turs/bootstrap/cache/compiled.php(9904): Laravel\Spark\Http\Middleware\VerifyUserHasTeam->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/turs/vendor/laravel/spark/src/Http/Middleware/CreateFreshApiToken.php(40): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/turs/bootstrap/cache/compiled.php(9904): Laravel\Spark\Http\Middleware\CreateFreshApiToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/turs/bootstrap/cache/compiled.php(10012): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/turs/bootstrap/cache/compiled.php(3164): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/turs/bootstrap/cache/compiled.php(13560): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/turs/bootstrap/cache/compiled.php(11983): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/turs/bootstrap/cache/compiled.php(13306): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/turs/bootstrap/cache/compiled.php(13243): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/turs/bootstrap/cache/compiled.php(9889): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/turs/bootstrap/cache/compiled.php(8191): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#61 /var/www/turs/bootstrap/cache/compiled.php(8182): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#62 /var/www/turs/bootstrap/cache/compiled.php(8173): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#63 /var/www/turs/bootstrap/cache/compiled.php(2471): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#64 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#65 /var/www/turs/bootstrap/cache/compiled.php(3226): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 /var/www/turs/bootstrap/cache/compiled.php(9904): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /var/www/turs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /var/www/turs/bootstrap/cache/compiled.php(9889): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /var/www/turs/bootstrap/cache/compiled.php(2415): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#70 /var/www/turs/bootstrap/cache/compiled.php(2399): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#71 /var/www/turs/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#72 {main}  

```

**Comment by jcergolj** [comment]
Let me know if this is fixed now.

**Comment by Samyoul** [comment]
Seems fixed.
